{
 "title": "Speedtest",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Current Download",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "download",
     "query": "SELECT last(\"value\")  / 125000 FROM \"download\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 125000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Upload",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Upload",
     "measurement": "download",
     "query": "SELECT \"up\" / 125000 FROM \"download\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "up" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Latency",
     "measurement": "download",
     "query": "SELECT \"latency\" FROM \"download\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Jitter",
     "measurement": "download",
     "query": "SELECT \"jitter\" FROM \"download\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "jitter" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean DL",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "download",
     "query": "SELECT mean(\"value\")  / 125000 FROM \"download\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 125000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean UL",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Upload",
     "measurement": "download",
     "query": "SELECT mean(\"up\") / 125000 FROM \"download\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "up" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean Ping",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Latency",
     "measurement": "download",
     "query": "SELECT mean(\"latency\") FROM \"download\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean Jitter",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Jitter",
     "measurement": "download",
     "query": "SELECT mean(\"jitter\") FROM \"download\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "jitter" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "download",
     "query": "SELECT (\"value\"  / 12500) FROM \"download\" WHERE $timeFilter \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " / 12500" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Readings",
   "type": "table-old",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "measurement": "download",
     "query": "SELECT \"value\"  / 125000, \"up\" / 125000, \"latency\", \"jitter\", \"server\" FROM \"download\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " / 125000" ], "type": "math" }
      ],
      [
       { "params": [ "up" ], "type": "field" },
       { "params": [ " / 12500" ], "type": "math" }
      ],
      [
       { "params": [ "latency" ], "type": "field" }
      ],
      [
       { "params": [ "jitter" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}